### ISSUE TITLE
Allowing PHP 5.6 apps to implement http-client

### ISSUE THREAD

**Issue by DragonBe** [php-fig/http-client#12]
Due to long migration time for some applications to be fully supported on PHP 7.x systems I would suggest to allow PHP 5.6 to implement this http-client. Looking at PSR-7 http-message, their requirement is even `>= 5.3.0`. For LTE support it allows systems to already make use of PSR's while their system (often not under their control) is still on 5.6.

So my suggestion in `composer.json`: `"php": "^5.6 || ^7.0",`

**Comment by Ocramius** [comment]
Removing the return type means releasing two completely different interfaces, leading to BC breaks in upgrades: https://github.com/php-fig/http-client/blob/496a823ef742b632934724bf769560c2a5c7c44e/src/ClientInterface.php#L19

Also, please don't encourage usage of PHP < 7.2, since 7.1 is [in security-only maintenance already](https://www.php.net/supported-versions.php), and people should use *new* packages with *new* software (like this PSR, which was [released in October 2018](https://github.com/php-fig/http-client/releases/tag/1.0.0)

**Comment by michaelcullum** [comment]
The main reason this cannot change is because PSRs are immutable once approved except for typo fixes but as Marco points out this would also be quite a severe BC break.

With regards to some of the thoughts behind making the decision to require PHP 7 originally though (in addition to Marco's point here and on the ZF issue about actively trying to push for newer versions where it's possible): A lot of the common/popular HTTP client libraries stated they'd require PHP 7 for releases implementing the PSR so it was decided that whilst it may have a small effect on adoption, it wouldn't be huge and therefore was worth the value of being able to fully type hint on the interface.

**Comment by michaelcullum** [comment]
Also, issues shouldn't be enabled on this repositories (that's a mistake, sorry). Issues would go on the main php-fig/fig-standards repository where the specs are located, this is just those as a composer installable package, so I'm going to disable issues on the repository in a couple of days (to give you a chance to see the above comments).

**Comment by DragonBe** [comment]
I read your feedback and acknowledge your point made. 

Feel free to close and remove the issue 😃
